#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Grades")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 擴充性方法定義
  partial void OnCreated();
  partial void Insert成績單(成績單 instance);
  partial void Update成績單(成績單 instance);
  partial void Delete成績單(成績單 instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["GradesConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<成績單> 成績單
	{
		get
		{
			return this.GetTable<成績單>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.成績單")]
public partial class 成績單 : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _學號;
	
	private string _姓名;
	
	private int _國文;
	
	private int _數學;
	
	private int _英文;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void On學號Changing(string value);
    partial void On學號Changed();
    partial void On姓名Changing(string value);
    partial void On姓名Changed();
    partial void On國文Changing(int value);
    partial void On國文Changed();
    partial void On數學Changing(int value);
    partial void On數學Changed();
    partial void On英文Changing(int value);
    partial void On英文Changed();
    #endregion
	
	public 成績單()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_學號", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string 學號
	{
		get
		{
			return this._學號;
		}
		set
		{
			if ((this._學號 != value))
			{
				this.On學號Changing(value);
				this.SendPropertyChanging();
				this._學號 = value;
				this.SendPropertyChanged("學號");
				this.On學號Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_姓名", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string 姓名
	{
		get
		{
			return this._姓名;
		}
		set
		{
			if ((this._姓名 != value))
			{
				this.On姓名Changing(value);
				this.SendPropertyChanging();
				this._姓名 = value;
				this.SendPropertyChanged("姓名");
				this.On姓名Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_國文", DbType="Int NOT NULL")]
	public int 國文
	{
		get
		{
			return this._國文;
		}
		set
		{
			if ((this._國文 != value))
			{
				this.On國文Changing(value);
				this.SendPropertyChanging();
				this._國文 = value;
				this.SendPropertyChanged("國文");
				this.On國文Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_數學", DbType="Int NOT NULL")]
	public int 數學
	{
		get
		{
			return this._數學;
		}
		set
		{
			if ((this._數學 != value))
			{
				this.On數學Changing(value);
				this.SendPropertyChanging();
				this._數學 = value;
				this.SendPropertyChanged("數學");
				this.On數學Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_英文", DbType="Int NOT NULL")]
	public int 英文
	{
		get
		{
			return this._英文;
		}
		set
		{
			if ((this._英文 != value))
			{
				this.On英文Changing(value);
				this.SendPropertyChanging();
				this._英文 = value;
				this.SendPropertyChanged("英文");
				this.On英文Changed();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
